text[0] = "This room doesn't exist."
text[1] = "Also, you're in the 'It's not called the living room anymore, it's called the DYING ROOM LOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLO'"

