target_x = 25;
target_y = 220;
target_room = R2YotsubaHomeLiving;
windowtitle ="It's not called the living room anymore, it's called the DYING ROOM LOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLOLOOLOLOLO"